### ISSUE TITLE
Barra de Rolagem no Estados

### ISSUE THREAD

**Issue by fabiolimaf** [tasafo/covid-19-brazil#2]
![Screenshot](https://user-images.githubusercontent.com/7782264/79057825-162ab100-7c3c-11ea-8cb7-258c5480b611.png)

**Comment by luizsanches** [comment]
@fabiolimaf resolvido com https://github.com/tasafo/covid-19-brazil/commit/699c94cf78f0e41c7fe35592f7d3fd2c94bfff68
